// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Restaurant struct {
	ID          uuid.UUID
	Name        *string
	Address     *string
	City        *string
	State       *string
	Star        int64
	PostalCode  *string
	Description *string
	UpdatedAt   *time.Time
	CreatedAt   time.Time
}
