// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Dish struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Images       []string
	Rating       *float64
	CreatedBy    uuid.UUID
	UpdatedAt    *time.Time
	CreatedAt    time.Time
}
