// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO dish (
  restaurant_id, name, images, rating, created_by, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, restaurant_id, name, images, rating, created_by, updated_at, created_at
`

type CreateMenuParams struct {
	RestaurantID uuid.UUID
	Name         string
	Images       []string
	Rating       *float64
	CreatedBy    uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Dish, error) {
	row := q.db.QueryRowContext(ctx, createMenu,
		arg.RestaurantID,
		arg.Name,
		pq.Array(arg.Images),
		arg.Rating,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Dish
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		pq.Array(&i.Images),
		&i.Rating,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
